blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/bloodbathwest-source/Music-AI-App/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/bloodbathwest-source/Music-AI-App/blob/main/README.md
    about: Check out our documentation for guides and API reference
